import csv
import json
import os
import subprocess
import re
import time
import queue
import signal
import logging
import threading
from dataclasses import dataclass, field
from datetime import date
from io import BytesIO
from pathlib import Path
from typing import Iterable, Optional, Tuple, List, Dict, Any
from urllib.parse import urljoin, urlparse

import requests
from requests.adapters import HTTPAdapter, Retry
from PIL import Image
from bs4 import BeautifulSoup

from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.chrome.service import Service as ChromeService
from selenium.webdriver.support import expected_conditions as EC
from selenium.webdriver.support.ui import WebDriverWait

import tempfile
import imageio_ffmpeg
from concurrent.futures import ProcessPoolExecutor

import config as dlcfg

# =========================
# Конфігурація
# =========================

@dataclass
class Config:
    input_file: Path = Path("links.txt")
    output_txt: Path = Path("output.txt")
    runtime_json: Path = Path("runtime_main.json")
    root_host: str = "https://adreal.gemius.com"
    out_dir_prefix: str = "Creatives"
    max_workers: int = 3
    screenshot_workers: int = 6
    youtube_workers: int = 6
    request_timeout: int = 15  # seconds
    page_load_timeout: int = 20  # selenium
    screenshot_queue_maxsize: int = 200
    user_agent: str = (
        "Mozilla/5.0 (Windows NT 10.0; Win64; x64) "
        "AppleWebKit/537.36 (KHTML, like Gecko) "
        "Chrome/123.0.0.0 Safari/537.36"
    )
    headless: bool = True
    window_size: str = "1920,1080"
    # Селектори для сторінки
    page_ready_selector: Tuple[By, str] = (By.CLASS_NAME, "page-content")
    element_screenshot_xpath: str = '//div[contains(@class,"card-body")]/div[1]'  # адаптуй під себе
    # скільки разів пробувати зняти медіа перш ніж робити скрін
    media_first_strategy: bool = True
    # video options
    max_video_height = 480
    ffmpeg_path: str = imageio_ffmpeg.get_ffmpeg_exe()



@dataclass
class RuntimeStats:
    """Агреговані метрики часу/кількості для подальшого запису в runtime JSON."""

    video_download_sec: float = 0.0
    youtube_download_sec: float = 0.0
    image_download_sec: float = 0.0
    html_download_sec: float = 0.0

    video_items: int = 0
    youtube_items: int = 0
    image_items: int = 0
    html_items: int = 0

    _lock: threading.Lock = field(default_factory=threading.Lock, repr=False)

    def add_video(self, sec: float) -> None:
        with self._lock:
            self.video_download_sec += float(sec)
            self.video_items += 1

    def add_youtube(self, sec: float, ok_count: int) -> None:
        with self._lock:
            self.youtube_download_sec += float(sec)
            self.youtube_items += int(ok_count)

    def add_image(self, sec: float) -> None:
        with self._lock:
            self.image_download_sec += float(sec)
            self.image_items += 1

    def add_html(self, sec: float) -> None:
        with self._lock:
            self.html_download_sec += float(sec)
            self.html_items += 1


# =========================
# Утиліти
# =========================

def cookies_to_netscape_file(cookies: List[dict]) -> str:
    """
    Приймає cookies з Selenium (driver.get_cookies()) і повертає ШЛЯХ до тимчасового
    Netscape cookie файлу. Файл треба видаляти вручну після використання.
    """
    now = int(time.time())
    tf = tempfile.NamedTemporaryFile("w", suffix=".cookies.txt", delete=False, encoding="utf-8")
    try:
        tf.write("# Netscape HTTP Cookie File\n")
        tf.write("# This file was generated by Selenium\n\n")
        for c in cookies:
            domain = c.get("domain", "")
            flag = "TRUE" if domain.startswith(".") else "FALSE"
            path = c.get("path", "/")
            secure = "TRUE" if c.get("secure", False) else "FALSE"
            expiry = int(c.get("expiry", now + 3600))
            name = c.get("name", "")
            value = c.get("value", "")
            tf.write(f"{domain}\t{flag}\t{path}\t{secure}\t{expiry}\t{name}\t{value}\n")
        tf.flush()
        return tf.name
    finally:
        tf.close()


def extract_videos_from_iframe(abs_iframe_url: str, session: requests.Session, cfg: Config) -> List[str]:
    """Завантажує HTML iframe і витягує відео-лінки (включно з <source>)."""
    try:
        r = session.get(abs_iframe_url, timeout=cfg.request_timeout)
        if r.status_code != 200 or not r.text:
            return []
        _imgs, vids, _ifr, _yt = find_media_blocks(r.text)
        # перетворюємо на абсолютні
        return [absolute_url(abs_iframe_url, v, cfg) for v in vids]
    except requests.RequestException:
        return []


def make_headless_driver(cfg: Config):
    """Локальний headless-драйвер для коротких задач (щоб не шарити воркерний браузер)."""
    opts = webdriver.ChromeOptions()

    opts.add_argument("--headless=new")
    opts.add_argument("--no-sandbox")
    opts.add_argument("--disable-dev-shm-usage")
    opts.add_argument("--disable-notifications")
    opts.add_argument("--disable-popup-blocking")
    opts.add_argument("--disable-background-networking")
    opts.add_argument("--disable-sync")
    opts.add_argument("--no-first-run")
    opts.add_argument("--no-default-browser-check")
    opts.add_argument("--mute-audio")
    opts.add_argument("--disable-gpu")  # можна лишити для CI
    opts.add_argument(
        "--disable-features=InterestCohortApi,PrivacySandboxAdsAPIs,MediaRouter,TranslateUI,OptimizationHints")
    opts.add_argument("--disable-client-side-phishing-detection")
    opts.add_argument("--disable-blink-features=AutomationControlled")
    opts.add_argument(f"--window-size={cfg.window_size}")
    opts.add_argument(f"user-agent={cfg.user_agent}")
    opts.add_argument("--log-level=3")

    # Глушимо банер "controlled by automated software" і зайві свічі
    opts.add_experimental_option("excludeSwitches", ["enable-automation", "enable-logging"])
    opts.add_experimental_option("useAutomationExtension", False)
    opts.add_argument("--enable-unsafe-swiftshader")

    # Менше зависань на навігації — самі чекаємо DOM
    opts.set_capability("pageLoadStrategy", "none")  # або 'eager'

    # ------------- ГОЛОВНЕ: прибрати stdout/stderr chromedriver -------------
    # Варіант 1 (рекомендовано): Selenium 4+ підтримує log_output=...
    # Windows: 'NUL', Linux/macOS: '/dev/null'
    null_dev = "NUL" if os.name == "nt" else "/dev/null"
    service = ChromeService(log_output=open(null_dev, "w"))  # приховає "DevTools listening..."

    # Варіант 2 (альтернатива для старіших версій selenium):
    # service = Service(log_path=null_dev)   # теж глушить лог

    try:
        drv = webdriver.Chrome(service=service, options=opts)
    except Exception:
        eopts = webdriver.EdgeOptions()
        eopts.add_argument("--headless=new")
        eopts.add_argument("--disable-gpu")
        eopts.add_argument("--remote-debugging-pipe")
        eopts.add_argument("--log-level=3")
        eopts.add_argument("--disable-speech-api")
        eopts.add_argument("--mute-audio")
        eopts.add_argument("--disable-notifications")
        eopts.add_argument("--disable-push-messaging")
        eopts.add_argument("--disable-background-networking")
        eopts.add_argument("--silent")
        eopts.add_argument("--enable-unsafe-swiftshader")
        eopts.add_experimental_option("excludeSwitches", ["enable-logging", "enable-automation"])
        eopts.add_argument("--disable-features=msEdgeDualEngine")  # глушить edge_dual_engine
        eopts.add_argument(f"user-agent={cfg.user_agent}")
        drv = webdriver.Edge(options=eopts)

    drv.set_page_load_timeout(cfg.page_load_timeout)
    return drv


def make_output_dir(cfg: Config, today: date) -> Path:
    base = Path(f"{cfg.out_dir_prefix}_{today.isoformat()}")
    candidate = base
    i = 1
    while candidate.exists():
        candidate = Path(f"{base}({i})")
        i += 1
    candidate.mkdir(parents=True, exist_ok=False)
    return candidate


def sanitize_name(s: str) -> str:
    s = re.sub(r"\s+", "", s)
    return re.sub(r"[^0-9A-Za-zА-Яа-яІіЇїЄєҐґ_-]+", "_", s)


def build_session(cfg: Config) -> requests.Session:
    session = requests.Session()
    session.headers.update({"User-Agent": cfg.user_agent})
    retries = Retry(
        total=5,
        backoff_factor=0.6,
        status_forcelist=(429, 500, 502, 503, 504),
        allowed_methods=frozenset(["GET", "HEAD"]),
        raise_on_status=False,
    )
    adapter = HTTPAdapter(max_retries=retries, pool_connections=100, pool_maxsize=100)
    session.mount("http://", adapter)
    session.mount("https://", adapter)
    return session


def read_links(path: Path, must_contain: str) -> List[str]:
    with path.open("r", encoding="utf-8", errors="ignore") as f:
        links = [ln.strip() for ln in f if ln.strip()]
    links = [ln for ln in links if must_contain in ln]
    return links


def save_bytes(path: Path, data: bytes) -> None:
    path.write_bytes(data)


def save_stream(path: Path, resp: requests.Response, chunk: int = 1024 * 1024) -> None:
    with path.open("wb") as f:
        for part in resp.iter_content(chunk_size=chunk):
            if part:
                f.write(part)


def save_image_safely(img_bytes: bytes, path: Path) -> None:
    try:
        with Image.open(BytesIO(img_bytes)) as im:
            try:
                im.save(path)
            except Exception:
                try:
                    im.convert("RGBA").save(path)
                except Exception:
                    im.convert("RGB").save(path)
    except Exception as e:
        raise RuntimeError(f"Bad image data: {e}")


def parse_brand(html: str) -> Optional[str]:
    # Приклад: шукаємо "Brand:" далі <a href="#">Name</a>
    soup = BeautifulSoup(html, "html.parser")
    # гнучкіше: знайдемо текст "Brand:" і сусіднє <a>
    brand_text = soup.find(string=lambda s: isinstance(s, str) and "Brand:" in s)
    if not brand_text:
        return None
    # частіше це в околі
    anchor = soup.select_one('a[href="#"]')
    if anchor and anchor.text.strip():
        return sanitize_name(anchor.text.strip())
    # fallback — грубим регексом
    m = re.search(r'Brand:.*?<a[^>]*>([^<]+)</a>', html, re.IGNORECASE | re.DOTALL)
    if m:
        return sanitize_name(m.group(1).strip())
    return None


def find_media_blocks(html: str) -> Tuple[List[str], List[str], List[str]]:
    """
    Повертає кортеж списків: (img_urls, video_urls, iframe_urls)
    Підтримує як відносні шляхи /files/... так і повні зовнішні.
    """
    soup = BeautifulSoup(html, "html.parser")
    main = soup.find(id="mainRow") or soup  # якщо нема, парсимо все

    img_urls = []
    for tag in main.find_all("img"):
        src = tag.get("src")
        if not src:
            continue
        img_urls.append(src)

    video_urls = []
    for tag in main.find_all("video"):
        src = tag.get("src")
        if not src:
            continue
        video_urls.append(src)

    video_urls = []
    for v in main.find_all("video"):
        # 1) <video src="...">
        if v.get("src"):
            video_urls.append(v.get("src"))
        # 2) <video><source src="..."></video>
        for s in v.find_all("source"):
            if s.get("src"):
                video_urls.append(s.get("src"))

    iframe_urls = []
    iframe_youtube_urls = []
    for tag in main.find_all("iframe"):
        src = tag.get("src")
        if not src:
            continue
        if "youtube.com" in src or "youtu.be" in src:
            iframe_youtube_urls.append(src)
            continue
        iframe_urls.append(src)

    return img_urls, video_urls, iframe_urls, iframe_youtube_urls


def absolute_url(base: str, url: str, cfg: Config) -> str:
    # Якщо зовнішній домен — віддаємо як є; якщо відносний — приєднуємо до root_host.
    if url.startswith(("http://", "https://")):
        return url
    return urljoin(base or cfg.root_host, url)


# =========================
# SABR детекція
# =========================

def is_sabr_only(yt_url: str, cookiefile_path: str | None = None) -> bool:
    """Перевірка через yt_dlp.extract_info (формати лише storyboard або відсутні)."""
    try:
        import yt_dlp
    except Exception:
        return False

    opts = {
        "quiet": True,
        "no_warnings": True,
        "skip_download": True,
        "extract_flat": False,
    }
    if cookiefile_path:
        opts["cookiefile"] = cookiefile_path

    try:
        with yt_dlp.YoutubeDL(opts) as ydl:
            info = ydl.extract_info(yt_url, download=False)
        fmts = info.get("formats", [])
        if not fmts:
            return True
        has_video = any(f.get("vcodec") != "none" and f.get("url") for f in fmts)
        is_only_storyboard = all(f.get("ext") == "mhtml" for f in fmts)
        return (not has_video) or is_only_storyboard
    except Exception as e:
        logging.warning(f"SABR перевірка не вдалася ({e}) → вважаємо SABR")
        return True

def download_youtube_core_mp(
    idx: int,
    yt_url: str,
    brand: str,
    out_dir: Path,
    cfg: Config,
    cookiefile_path: Optional[str] = None,
) -> tuple[bool, float]:
    """
    Завантажує YouTube відео у окремому процесі без Selenium.

    Повертає (ok, elapsed_sec) щоб головний процес міг порахувати час по відео.
    """
    start = time.perf_counter()
    ok = False

    try:
        import yt_dlp  # type: ignore

        # 1) SABR/порожні формати: якщо там немає відео — не качаємо
        try:
            opts_probe: dict = {
                "quiet": True,
                "no_warnings": True,
                "skip_download": True,
                "extract_flat": False,
            }
            if cookiefile_path:
                opts_probe["cookiefile"] = cookiefile_path

            with yt_dlp.YoutubeDL(opts_probe) as ydl:
                info = ydl.extract_info(yt_url, download=False)

            fmts = info.get("formats", []) or []
            if not fmts or all(f.get("ext") == "mhtml" for f in fmts):
                logging.warning(f"[{idx}] SABR-only: пропускаємо завантаження.")
                return False, time.perf_counter() - start
        except Exception as exc:
            logging.warning(f"[{idx}] SABR перевірка не вдалася: {exc}")

        # 2) Параметри для завантаження
        out_path = out_dir / f"{idx}_{brand or 'NA'}_{date.today().isoformat()}.mp4"
        ydl_opts: dict = {
            "outtmpl": str(out_path),
            "quiet": False,          # можна увімкнути лог для дебагу
            "no_warnings": True,
            "noplaylist": True,
            "format": (
                f"best[ext=mp4][height<={cfg.max_video_height}]"
                f"/best[height<={cfg.max_video_height}]"
            ),
            "nopart": True,
            "updatetime": False,
            "merge_output_format": None,
            "ffmpeg_location": cfg.ffmpeg_path,
            "ignoreerrors": True,
            "concurrent_fragment_downloads": 3,
            "extractor_args": {"youtube": {"player_client": ["android", "web"]}},
        }
        if cookiefile_path:
            ydl_opts["cookiefile"] = cookiefile_path

        # 3) Основна спроба
        try:
            with yt_dlp.YoutubeDL(ydl_opts) as ydl:
                ydl.download([yt_url])
            logging.info(f"[{idx}] YouTube(proc) збережено: {out_path.name}")
            ok = True
        except Exception as exc:
            logging.warning(f"[{idx}] yt_dlp primary помилка: {exc}")

        # 4) fallback
        if not ok:
            try:
                ydl_opts["format"] = "best"
                with yt_dlp.YoutubeDL(ydl_opts) as ydl:
                    ydl.download([yt_url])
                logging.info(f"[{idx}] YouTube(proc-fallback) збережено: {out_path.name}")
                ok = True
            except Exception as exc:
                logging.error(f"[{idx}] fallback не вдалось: {exc}")

    except Exception as exc:
        logging.error(f"[{idx}] YouTube(proc) критична помилка: {exc}")

    return ok, time.perf_counter() - start


def download_youtube_core(
        drv,
        idx: int,
        parent_page_url: str,
        brand: str,
        out_dir: Path,
        cfg: Config,
        yt_pool: "YouTubeProcessPool",
) -> bool:
    import yt_dlp
    cookiefile_path = None
    try:
        drv.get(parent_page_url)
        # знайти iframe
        try:
            iframe_el = WebDriverWait(drv, cfg.page_load_timeout).until(
                EC.presence_of_element_located(
                    (By.XPATH, "//iframe[contains(@src, 'youtube.com') or contains(@src, 'youtu.be')]")
                )
            )
        except Exception:
            logging.error(f"[{idx}] Не знайдено YouTube iframe на сторінці")
            return False

        drv.switch_to.frame(iframe_el)
        yt_url = None
        try:
            link_el = WebDriverWait(drv, 3).until(
                EC.presence_of_element_located((By.CLASS_NAME, "ytp-impression-link"))
            )
            yt_url = link_el.get_attribute("href")
        except Exception:
            pass
        if not yt_url:
            drv.switch_to.default_content()
            yt_url = iframe_el.get_attribute("src")

        # куки
        cookies = drv.get_cookies()
        cookiefile_path = cookies_to_netscape_file(cookies)

        # замість прямого yt_dlp — відправляємо у пул процесів
        yt_pool.enqueue(idx, yt_url, brand, cookiefile_path)
        logging.info(f"[{idx}] YouTube завдання відправлено у процес")
        return True

    except Exception as e:
        logging.error(f"[\033[32m{idx}\033[0m] YouTube помилка: {e}")
        return False
    finally:
        if cookiefile_path:
            try:
                os.remove(cookiefile_path)
            except Exception:
                pass


class YouTubeWorker(threading.Thread):
    def __init__(self, cfg: Config, out_dir: Path, yt_pool: "YouTubeProcessPool"):
        super().__init__(daemon=True)
        self.cfg = cfg
        self.out_dir = out_dir
        self.yt_pool = yt_pool
        self.tasks: "queue.Queue[Tuple[int, str, str]]" = queue.Queue(maxsize=50)
        self._stop_event = threading.Event()
        self._drv = make_headless_driver(cfg)

    def run(self):
        while not self._stop_event.is_set():
            try:
                idx, url, brand = self.tasks.get(timeout=0.5)
            except queue.Empty:
                continue
            try:
                download_youtube_core(self._drv, idx, url, brand, self.out_dir, self.cfg, self.yt_pool)
            except Exception as e:
                logging.error(f"[\033[32m[YTW]\033[0m] #[\033[32m{idx}\033[0m] помилка: {e}")
            finally:
                self.tasks.task_done()
        try:
            self._drv.quit()
        except Exception:
            pass

    def enqueue(self, idx: int, url: str, brand: str):
        self.tasks.put((idx, url, brand))

    def stop(self):
        self._stop_event.set()

class YouTubeProcessPool:
    def __init__(self, cfg: Config, out_dir: Path):
        self.cfg = cfg
        self.out_dir = out_dir
        self.executor = ProcessPoolExecutor(max_workers=cfg.youtube_workers)
        self._futures = []
        self._lock = threading.Lock()

    def enqueue(
        self,
        idx: int,
        yt_url: str,
        brand: str,
        cookiefile_path: str | None = None,
    ) -> None:
        """Передає завдання у окремий процес (асинхронно)."""
        fut = self.executor.submit(
            download_youtube_core_mp,
            idx,
            yt_url,
            brand,
            self.out_dir,
            self.cfg,
            cookiefile_path,
        )
        with self._lock:
            self._futures.append(fut)

    def shutdown_and_collect(self) -> tuple[int, float]:
        """
        Коректне завершення + збір статистики.
        Повертає (ok_count, total_elapsed_sec) по YouTube-відео.
        """
        self.executor.shutdown(wait=True)

        ok_count = 0
        elapsed_sum = 0.0

        with self._lock:
            futures = list(self._futures)

        for fut in futures:
            try:
                ok, elapsed = fut.result()
                if ok:
                    ok_count += 1
                elapsed_sum += float(elapsed)
            except Exception:
                # якщо процес упав/викинув виключення — просто не рахуємо ok,
                # але врахувати час неможливо
                continue

        return ok_count, elapsed_sum


# =========================
# Скріншот-воркер
# =========================

class ScreenshotWorker(threading.Thread):
    def __init__(self, cfg: Config, out_dir: Path, tasks_queue: "queue.Queue[Tuple[int,str,str]]", runtime_stats: RuntimeStats):
        super().__init__(daemon=True)
        self.cfg = cfg
        self.out_dir = out_dir
        self.tasks = tasks_queue   # <- тепер використовуємо зовнішню чергу
        self.runtime_stats = runtime_stats
        self._stop_event = threading.Event()
        self._driver = None


    def run(self):
        self._driver = self._make_driver()
        try:
            while not self._stop_event.is_set():  # <- виправлено
                try:
                    number, url, out_name = self.tasks.get(timeout=0.25)
                except queue.Empty:
                    continue
                try:
                    st0 = time.perf_counter()
                    self._take_screenshot(url, self.out_dir / out_name)
                    self.runtime_stats.add_image(time.perf_counter() - st0)
                except Exception as e:
                    logging.error(f"[screenshot] #{number} failed: {e}")
                finally:
                    self.tasks.task_done()
        finally:
            if self._driver:
                try:
                    self._driver.quit()
                except Exception:
                    pass

    def stop(self):
        self._stop_event.set()  # <- виправлено

    def enqueue(self, number: int, url: str, out_name: str):
        self.tasks.put((number, url, out_name))

    def join_until_empty(self):
        self.tasks.join()

    def _make_driver(self):
        # Chrome за замовчуванням; якщо немає — пробуємо Edge.
        opts = webdriver.ChromeOptions()
        if self.cfg.headless:
            opts.add_argument("--headless=new")
            opts.add_argument("--disable-gpu")
            opts.add_argument("--log-level=3")
        opts.add_argument(f"--window-size={self.cfg.window_size}")
        opts.add_experimental_option("excludeSwitches", ["enable-logging"])
        opts.add_argument(f"user-agent={self.cfg.user_agent}")

        try:
            driver = webdriver.Chrome(options=opts)
        except Exception:
            # fallback: Edge
            eopts = webdriver.EdgeOptions()
            if self.cfg.headless:
                eopts.add_argument("--headless=new")
                eopts.add_argument("--disable-gpu")
                eopts.add_argument("--log-level=3")
            eopts.add_argument(f"--window-size={self.cfg.window_size}")
            eopts.add_experimental_option("excludeSwitches", ["enable-logging"])
            eopts.add_argument(f"user-agent={self.cfg.user_agent}")
            driver = webdriver.Edge(options=eopts)

        driver.set_page_load_timeout(self.cfg.page_load_timeout)
        return driver

    def _take_screenshot(self, url: str, out_path: Path):
        drv = self._driver
        drv.get(url)
        WebDriverWait(drv, self.cfg.page_load_timeout).until(
            EC.visibility_of_element_located(self.cfg.page_ready_selector)
        )

        # Масштабування вікна так, щоб елемент помістився
        drv.execute_script("""
            const el = document.evaluate(arguments[0], document, null, XPathResult.FIRST_ORDERED_NODE_TYPE, null).singleNodeValue;
            if (!el) return;
            document.body.style.zoom = 1;

            const elementWidth = el.clientWidth;
            const elementHeight = el.clientHeight;
            const windowWidth = window.innerWidth;
            const windowHeight = window.innerHeight;

            const widthRatio = windowWidth / Math.max(1, elementWidth);
            const heightRatio = windowHeight / Math.max(1, elementHeight);
            const zoomFactor = Math.min(widthRatio, heightRatio, 1);

            document.body.style.zoom = zoomFactor;

            const rect = el.getBoundingClientRect();
            const scrollLeft = window.pageXOffset + rect.left * zoomFactor - (windowWidth - rect.width * zoomFactor) / 2;
            const scrollTop  = window.pageYOffset + rect.top * zoomFactor  - (windowHeight - rect.height * zoomFactor) / 2;

            const extra = elementHeight * 0.2 * zoomFactor;
            window.scrollTo({ top: scrollTop + extra, left: scrollLeft, behavior: 'instant' });
        """, self.cfg.element_screenshot_xpath)

        # якщо елемент знайдеться — робимо скрін елемента; інакше — фулпейдж
        try:
            el = drv.find_element(By.XPATH, self.cfg.element_screenshot_xpath)
            el.screenshot(str(out_path))
        except Exception:
            drv.save_screenshot(str(out_path))


# =========================
# Обробка одного лінка
# =========================

def process_link(
    idx: int,
    url: str,
    session: requests.Session,
    cfg: Config,
    out_dir: Path,
    shot_queue: "queue.Queue[Tuple[int, str, str]]",
    yt_enqueue,
    runtime_stats: RuntimeStats,
) -> Tuple[str, int, str, str, str]:
    """
    Повертає: (link, http_status, brand, number_or_empty, media_type)

    number_or_empty = str(idx) якщо щось збережено (медіа або скрін), інакше "".
    media_type: "video" | "html" | "banner" | ""
    """
    t0 = time.perf_counter()
    brand = ""
    saved_any = False
    media_type = ""

    try:
        resp = session.get(url, timeout=cfg.request_timeout)
    except requests.RequestException as e:
        logging.error(f"[{idx}] GET failed: {e}")
        return url, 0, brand, "", ""

    status = resp.status_code
    if status != 200 or not resp.text:
        return url, status, brand, "", ""

    brand = parse_brand(resp.text) or ""

    imgs, videos, iframes, iframes_youtube = find_media_blocks(resp.text)

    if cfg.media_first_strategy:
        media_type = try_save_media(
            idx=idx,
            page_url=url,
            brand=brand,
            img_urls=imgs,
            video_urls=videos,
            iframe_urls=iframes,
            iframes_youtube_urls=iframes_youtube,
            session=session,
            cfg=cfg,
            out_dir=out_dir,
            yt_enqueue=yt_enqueue,
            runtime_stats=runtime_stats,
        )

        # Якщо HTML-вигрузка вимкнена в config.py і сторінка може дати лише .html —
        # вважаємо, що "нічого не вивантажили" (без змін у самій логіці save_*).
        if media_type == dlcfg.HTML_DISABLED_RESULT:
            logging.info(f"[{idx}] HTML disabled → mark as not downloaded")
            return url, status, "", "", ""

        saved_any = bool(media_type)

    if not saved_any:
        if dlcfg.ALLOW_SCREENSHOT_FALLBACK:
            out_name = f"{idx}_{brand or 'NA'}_{date.today().isoformat()}.png"
            shot_queue.put((idx, url, out_name))
            saved_any = True
            media_type = "banner"  # скрін банеру
        else:
            # Нічого не зберігаємо (корисно для дебагу або якщо хочете лише відео тощо)
            saved_any = False
            media_type = ""

    dt = time.perf_counter() - t0
    logging.info(
        f"[[32m{idx}[0m] done in {dt:.2f}s (saved={saved_any}, type={media_type})"
    )
    return url, status, brand, str(idx) if saved_any else "", media_type


def try_save_media(
    *,
    idx: int,
    page_url: str,
    brand: str,
    img_urls: Iterable[str],
    video_urls: Iterable[str],
    iframe_urls: Iterable[str],
    iframes_youtube_urls: Iterable[str],
    session: requests.Session,
    cfg: Config,
    out_dir: Path,
    yt_enqueue,
    runtime_stats: RuntimeStats,
) -> str:
    today = date.today().isoformat()

    # ---- зображення (якщо колись знову увімкнете) ----
    # for src in img_urls:
    #     abs_url = absolute_url(page_url, src, cfg)
    #     st0 = time.perf_counter()
    #     try:
    #         r = session.get(abs_url, timeout=cfg.request_timeout)
    #         if r.status_code != 200:
    #             continue
    #         ext = guess_ext_from_headers_or_url(r, abs_url, default=".jpg")
    #         try:
    #             with Image.open(BytesIO(r.content)) as im:
    #                 if im.width < 36 and im.height < 36:
    #                     continue
    #         except Exception:
    #             continue
    #         out = out_dir / f"{idx}_{brand or 'NA'}_{today}{ext}"
    #         save_image_safely(r.content, out)
    #         runtime_stats.add_image(time.perf_counter() - st0)
    #         return "image"
    #     except requests.RequestException:
    #         continue

    # ---- відео (пряме) ----
    for src in video_urls:
        abs_url = absolute_url(page_url, src, cfg)
        st0 = time.perf_counter()
        try:
            r = session.get(abs_url, timeout=cfg.request_timeout, stream=True)
            if r.status_code != 200:
                continue
            out = out_dir / f"{idx}_{brand or 'NA'}_{today}.mp4"
            save_stream(out, r, cfg.max_video_height * cfg.max_video_height)
            runtime_stats.add_video(time.perf_counter() - st0)
            return "video"
        except requests.RequestException:
            continue

    # ---- iframe ----
    for src in iframe_urls:
        abs_url = absolute_url(page_url, src, cfg)

        # 1) пробуємо витягти відео з контенту iframe
        inner_videos = extract_videos_from_iframe(abs_url, session, cfg)
        for v in inner_videos:
            st0 = time.perf_counter()
            try:
                r = session.get(v, timeout=cfg.request_timeout, stream=True)
                if r.status_code != 200:
                    continue
                out = out_dir / f"{idx}_{brand or 'NA'}_{today}.mp4"
                save_stream(out, r, cfg.max_video_height * cfg.max_video_height)
                runtime_stats.add_video(time.perf_counter() - st0)
                return "video"
            except requests.RequestException:
                continue

        # 2) якщо відео не знайшли — опційно збережемо HTML як є
        st0 = time.perf_counter()
        try:
            r = session.get(abs_url, timeout=cfg.request_timeout)
            if r.status_code != 200 or not r.content:
                continue

            # HTML може бути вимкнений (щоб не плодити .html файли)
            if not dlcfg.ALLOW_HTML_DOWNLOAD:
                # 1) "mark_failed" — повертаємо спец-токен, щоб process_link записав
                #    як "нічого не вивантажили" (порожні number/type)
                if dlcfg.HTML_DISABLED_BEHAVIOR == "mark_failed":
                    return dlcfg.HTML_DISABLED_RESULT
                # 2) "screenshot" — просто ігноруємо цей iframe і дамо впасти у скрін
                continue

            out = out_dir / f"{idx}_{brand or 'NA'}_{today}.html"
            save_bytes(out, r.content)
            runtime_stats.add_html(time.perf_counter() - st0)
            return "html"
        except requests.RequestException:
            continue

    # ---- YouTube iframe ----
    if iframes_youtube_urls:
        # тут нам треба Selenium, щоб витягнути справжній yt_url і куки.
        # Робимо це через YouTubeWorker, який потім кидає задачу в процес-пул.
        yt_enqueue(idx, page_url, brand)
        return "video"

    return ""


def guess_ext_from_headers_or_url(resp: requests.Response, url: str, default: str = ".bin") -> str:
    ctype = resp.headers.get("Content-Type", "")
    if "image/png" in ctype:
        return ".png"
    if "image/jpeg" in ctype:
        return ".jpg"
    if "image/gif" in ctype:
        return ".gif"
    if "video/mp4" in ctype:
        return ".mp4"

    # з URL
    path = urlparse(url).path.lower()
    for ext in (".png", ".jpg", ".jpeg", ".gif", ".mp4", ".webm"):
        if path.endswith(ext):
            return ".jpg" if ext == ".jpeg" else ext
    return default


# =========================
# Головний сценарій
# =========================

def setup_logging():
    logging.basicConfig(
        level=logging.INFO,
        format="%(asctime)s %(levelname)s | %(message)s",
        datefmt="%H:%M:%S",
    )


def run(cfg: Optional[Config] = None) -> Dict[str, Any]:
    """Запускає вигрузку креативів.

    Повертає runtime-метрики як dict, щоб зовнішній раннер міг сам вирішити,
    що і куди писати (JSON, логування, тощо).
    """
    setup_logging()
    cfg = cfg or Config()
    today = date.today()

    links = read_links(cfg.input_file, must_contain=cfg.root_host)
    if not links:
        logging.warning("Немає валідних лінків у links.txt")
        return {
            "download_time_total_wall_sec": 0.0,
            "download_time_video_direct_sec": 0.0,
            "download_time_video_youtube_sec": 0.0,
            "download_time_images_sec": 0.0,
            "download_time_html_sec": 0.0,
            "downloaded_video_direct_items": 0,
            "downloaded_video_youtube_items": 0,
            "downloaded_image_items": 0,
            "downloaded_html_items": 0,
        }

    out_dir = make_output_dir(cfg, today)
    session = build_session(cfg)

    runtime_stats = RuntimeStats()

    # воркери для скрінів
    shared_shot_queue = queue.Queue(maxsize=cfg.screenshot_queue_maxsize)
    shot_workers = [ScreenshotWorker(cfg, out_dir, shared_shot_queue, runtime_stats) for _ in range(cfg.screenshot_workers)]
    for w in shot_workers:
        w.start()

    # воркери для YouTube (Selenium -> кидає в процес-пул)
    yt_pool = YouTubeProcessPool(cfg, out_dir)
    yt_workers = [YouTubeWorker(cfg, out_dir, yt_pool) for _ in range(cfg.youtube_workers)]
    for w in yt_workers:
        w.start()

    def yt_enqueue(idx: int, parent_page_url: str, brand: str) -> None:
        # простий round-robin, щоб розкидати задачі між воркерами
        if not yt_workers:
            return
        worker = yt_workers[(idx - 1) % len(yt_workers)]
        worker.enqueue(idx, parent_page_url, brand)

    # обробка лінків у пулі потоків
    from concurrent.futures import ThreadPoolExecutor, as_completed

    t0 = time.perf_counter()
    results: List[Tuple[str, int, str, str, str]] = []

    # коректний вихід Ctrl+C
    stop_event = threading.Event()

    def _sigint(_sig, _frm):
        stop_event.set()
        logging.warning("Зупинка за сигналом. Чекаю завершення задач…")

    signal.signal(signal.SIGINT, _sigint)

    try:
        with ThreadPoolExecutor(max_workers=cfg.max_workers) as ex:
            futs = {
                ex.submit(
                    process_link,
                    i,
                    link,
                    session,
                    cfg,
                    out_dir,
                    shared_shot_queue,
                    yt_enqueue,
                    runtime_stats,
                ): i
                for i, link in enumerate(links, start=1)
            }
            total = len(futs)
            done = 0
            for fut in as_completed(futs):
                if stop_event.is_set():
                    break
                try:
                    results.append(fut.result())
                except Exception as e:
                    logging.error(f"Помилка в задачі: {e}")
                done += 1
                if done % 50 == 0 or done == total:
                    elapsed = time.perf_counter() - t0
                    logging.info(f"Прогрес: [1;32m{done}[0m/[1;32m{total}[0m ({done / total * 100:.1f}%), {elapsed:.1f}s")

    finally:
        # 1) дочекайся, поки всі скріни доробляться
        shared_shot_queue.join()
        for w in shot_workers:
            w.stop()
        for w in shot_workers:
            w.join(timeout=5)

        # 2) дочекайся, поки Selenium-ютуб-черги спорожніють
        for w in yt_workers:
            w.tasks.join()
            w.stop()
        for w in yt_workers:
            w.join(timeout=5)

        # 3) дочекайся, поки процеси yt_dlp завершаться + зберемо статистику
        yt_ok_count, yt_elapsed_sum = yt_pool.shutdown_and_collect()
        runtime_stats.add_youtube(yt_elapsed_sum, ok_count=yt_ok_count)
        # NOTE: youtube_items — це кількість ок успішних. elapsed_sum — сумарний час у процесах.

    # запис TXT з додатковою колонкою type
    with cfg.output_txt.open("w", newline="", encoding="utf-8") as f:
        w = csv.writer(f)
        w.writerow(["link", "status", "brand", "number", "type"])
        for row in results:
            w.writerow(row)

    # runtime-метрики (повертаємо dict; писати у файл — справа раннера/CLI)
    total_elapsed = time.perf_counter() - t0
    runtime_payload: Dict[str, Any] = {
        "download_time_total_wall_sec": float(total_elapsed),
        "download_time_video_direct_sec": float(runtime_stats.video_download_sec),
        "download_time_video_youtube_sec": float(runtime_stats.youtube_download_sec),
        "download_time_images_sec": float(runtime_stats.image_download_sec),
        "download_time_html_sec": float(runtime_stats.html_download_sec),
        "downloaded_video_direct_items": int(runtime_stats.video_items),
        "downloaded_video_youtube_items": int(runtime_stats.youtube_items),
        "downloaded_image_items": int(runtime_stats.image_items),
        "downloaded_html_items": int(runtime_stats.html_items),
    }

    logging.info(f"Готово. Оброблено {len(results)} посилань за [93m{total_elapsed:.1f}s[00m")
    logging.info(f"Вихідні файли: [91m{out_dir}[00m | Лог TXT: [91m{cfg.output_txt}[00m")

    return runtime_payload


def cli() -> int:
    """CLI entrypoint"""
    cfg = Config()
    runtime_payload = run(cfg)
    try:
        cfg.runtime_json.write_text(
            json.dumps(runtime_payload, ensure_ascii=False, indent=2),
            encoding="utf-8",
        )
    except Exception as exc:
        logging.warning(f"Не вдалося записати runtime JSON {cfg.runtime_json}: {exc}")
        return 2
    return 0


if __name__ == "__main__":
    run()
